name: Keep Render Servers Alive
on:
  schedule:
    - cron: "*/7 * * * *"   # run every 7 minutes
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Add random delay (0–120s)
        run: sleep $((RANDOM % 120))
      - name: Ping servers
        run: |
          # Add your server URLs here, separated by spaces
          for url in https://server-kma3.onrender.com/ ; do
            echo "Pinging $url..."
            if curl -s --max-time 10 $url > /dev/null; then
              echo "✅ $url is UP"
            else
              echo "❌ $url is DOWN"
              curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
                -d chat_id=${{ secrets.CHAT_ID }} \
                -d text="⚠️ Server DOWN: $url"
            fi
          done
