name: Keep Render Servers Alive

on:
  schedule:
    # Runs every 7 minutes to keep the free-tier services alive
    - cron: "*/7 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      
    steps:
      - name: Add a random delay to avoid simultaneous pings
        run: sleep $((RANDOM % 120)) # Random wait up to 2 minutes

      - name: Ping each server
        env:
          SERVER_URLS: ${{ secrets.SERVER_URLS }}
          SERVER_NAMES: ${{ secrets.SERVER_NAMES }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          read -ra urls <<< "$SERVER_URLS"
          read -ra names <<< "$SERVER_NAMES"

          for i in "${!urls[@]}"; do
            url="${urls[$i]}"
            name="${names[$i]}"

            echo "Pinging $name ($url)..."

            if curl -s --max-time 10 -A "Mozilla/5.0" "$url" > /dev/null; then
              echo "✅ $name is UP"

              # Send a heartbeat message to Telegram every 7 minutes
              message="💓 Heartbeat: '$name' is UP!"
              curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
                -d chat_id="$CHAT_ID" \
                -d text="$message"

            else
              echo "❌ $name is DOWN. Starting retry mechanism..."
              is_server_up=false

              for attempt in {1..3}; do
                echo "Retry attempt $attempt/3 in 5 minutes..."
                sleep 300

                echo "Pinging $name ($url) again..."
                if curl -s --max-time 10 -A "Mozilla/5.0" "$url" > /dev/null; then
                  echo "✅ $name is back UP!"
                  is_server_up=true
                  message="✅ Your website '$name' is back online!"
                  curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
                    -d chat_id="$CHAT_ID" \
                    -d text="$message"
                  break
                else
                  echo "❌ $name is still DOWN."
                fi
              done

              if [ "$is_server_up" = false ]; then
                echo "Server $name did not recover. Sending notification."
                message="⚠️ Your website '$name' is not live. Something went wrong."
                curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
                  -d chat_id="$CHAT_ID" \
                  -d text="$message"
              fi
            fi
          done
